### ISSUE TITLE
Improvements / Feature Requests

### ISSUE THREAD

**Issue by girst** [notiocide/android-minesweeper#7]
Hi, first of all, thank you for this app, it looks really nice! I am looking for a Free (as in Freedom) minesweeper implementation for Android for quite a long of time, and this comes really close. I do have some requests, though:

* allow zooming (out): sometimes I would like to get a better overview of things
* "flagging mode": a button that inverts what short/long clicking does (i.e. click the button, then every minefeld-cell gets flagged instead of opened; long click one to open one. click the button again and it's back to normal)
* require only a single click to chord (open surrounding cells of an opened one, iff the exact number of flags are set)
* long click is too long (maybe make it configurable?)

I know that's a lot, and I'd like to help, but don't really know anything about Android programming. I'd chip in a beer (or a few) to show my support any time, though. ;-)

On another note, would you be O.K. with me pitching this app to F-Droid? [F-Droid](https://f-droid.org) is a repository and "app store" for FOSS apps.

**Comment by svby** [comment]
Thanks for the feedback 😃

I haven't worked on this project in a while but I definitely feel like improving it when I have time in the near future; I'm quite sure I could implement most of these ideas, apart from the long-click duration, which is set by the OS (there are a few workarounds.) I'd also like to fix a few bugs I found myself and clean up the project a bit.

I don't have any experience with packaging/distributing apps, but I suppose I would be fine with that.

**Comment by svby** [comment]
Hi,

I know it's been a really long while (sorry); I'm about to wrap up the last of my exams and found a bit of free time to take care of some issues.

I've still got the zoom functionality to take care of, but I should have time to do that after everything else is done in a few weeks.

**Comment by girst** [comment]
Great to hear, thanks!

**Comment by svby** [comment]
My attempts to resolve this issue have had pretty awful timing, thanks to pandemic delays. I _**will**_ get to the last part of this issue after uni exams, which are in 2-3 weeks, so I'll close this until then.
